export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <head>
        <title>Alexandre Pozzi</title>
      </head>
      <body>{children}</body>
    </html>
  );
}
